"""remove password from user

Revision ID: 3b90e0354a60
Revises: e074536efbd9
Create Date: 2021-05-27 14:12:11.349110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b90e0354a60'
down_revision = 'e074536efbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
